version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000/api

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - EMAIL_USER=sakshee907@gmail.com
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped



